// Generated by gencpp from file ros_linetracking_pub/linetracking_data.msg
// DO NOT EDIT!


#ifndef ROS_LINETRACKING_PUB_MESSAGE_LINETRACKING_DATA_H
#define ROS_LINETRACKING_PUB_MESSAGE_LINETRACKING_DATA_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ros_linetracking_pub
{
template <class ContainerAllocator>
struct linetracking_data_
{
  typedef linetracking_data_<ContainerAllocator> Type;

  linetracking_data_()
    : readings()  {
    }
  linetracking_data_(const ContainerAllocator& _alloc)
    : readings(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _readings_type;
  _readings_type readings;





  typedef boost::shared_ptr< ::ros_linetracking_pub::linetracking_data_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ros_linetracking_pub::linetracking_data_<ContainerAllocator> const> ConstPtr;

}; // struct linetracking_data_

typedef ::ros_linetracking_pub::linetracking_data_<std::allocator<void> > linetracking_data;

typedef boost::shared_ptr< ::ros_linetracking_pub::linetracking_data > linetracking_dataPtr;
typedef boost::shared_ptr< ::ros_linetracking_pub::linetracking_data const> linetracking_dataConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ros_linetracking_pub::linetracking_data_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ros_linetracking_pub::linetracking_data_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ros_linetracking_pub

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'ros_linetracking_pub': ['/home/ubuntu/catkin_ws/src/line_tracking_pub/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ros_linetracking_pub::linetracking_data_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_linetracking_pub::linetracking_data_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_linetracking_pub::linetracking_data_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_linetracking_pub::linetracking_data_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_linetracking_pub::linetracking_data_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_linetracking_pub::linetracking_data_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ros_linetracking_pub::linetracking_data_<ContainerAllocator> >
{
  static const char* value()
  {
    return "790f38aeabddcc73abb1ebbc6fb37849";
  }

  static const char* value(const ::ros_linetracking_pub::linetracking_data_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x790f38aeabddcc73ULL;
  static const uint64_t static_value2 = 0xabb1ebbc6fb37849ULL;
};

template<class ContainerAllocator>
struct DataType< ::ros_linetracking_pub::linetracking_data_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ros_linetracking_pub/linetracking_data";
  }

  static const char* value(const ::ros_linetracking_pub::linetracking_data_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ros_linetracking_pub::linetracking_data_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# line tracking data is float array with five elements\n\
\n\
float32[] readings\n\
";
  }

  static const char* value(const ::ros_linetracking_pub::linetracking_data_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ros_linetracking_pub::linetracking_data_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.readings);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct linetracking_data_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ros_linetracking_pub::linetracking_data_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ros_linetracking_pub::linetracking_data_<ContainerAllocator>& v)
  {
    s << indent << "readings[]" << std::endl;
    for (size_t i = 0; i < v.readings.size(); ++i)
    {
      s << indent << "  readings[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.readings[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROS_LINETRACKING_PUB_MESSAGE_LINETRACKING_DATA_H
