// Generated by gencpp from file ros_imu_pub/imu_data.msg
// DO NOT EDIT!


#ifndef ROS_IMU_PUB_MESSAGE_IMU_DATA_H
#define ROS_IMU_PUB_MESSAGE_IMU_DATA_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ros_imu_pub
{
template <class ContainerAllocator>
struct imu_data_
{
  typedef imu_data_<ContainerAllocator> Type;

  imu_data_()
    : heading(0.0)
    , roll(0.0)
    , pitch(0.0)
    , lin_x(0.0)
    , lin_y(0.0)
    , lin_z(0.0)  {
    }
  imu_data_(const ContainerAllocator& _alloc)
    : heading(0.0)
    , roll(0.0)
    , pitch(0.0)
    , lin_x(0.0)
    , lin_y(0.0)
    , lin_z(0.0)  {
  (void)_alloc;
    }



   typedef float _heading_type;
  _heading_type heading;

   typedef float _roll_type;
  _roll_type roll;

   typedef float _pitch_type;
  _pitch_type pitch;

   typedef float _lin_x_type;
  _lin_x_type lin_x;

   typedef float _lin_y_type;
  _lin_y_type lin_y;

   typedef float _lin_z_type;
  _lin_z_type lin_z;





  typedef boost::shared_ptr< ::ros_imu_pub::imu_data_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ros_imu_pub::imu_data_<ContainerAllocator> const> ConstPtr;

}; // struct imu_data_

typedef ::ros_imu_pub::imu_data_<std::allocator<void> > imu_data;

typedef boost::shared_ptr< ::ros_imu_pub::imu_data > imu_dataPtr;
typedef boost::shared_ptr< ::ros_imu_pub::imu_data const> imu_dataConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ros_imu_pub::imu_data_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ros_imu_pub::imu_data_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ros_imu_pub

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'ros_imu_pub': ['/home/ubuntu/catkin_ws/src/ros_imu_pub/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ros_imu_pub::imu_data_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_imu_pub::imu_data_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_imu_pub::imu_data_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_imu_pub::imu_data_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_imu_pub::imu_data_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_imu_pub::imu_data_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ros_imu_pub::imu_data_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1347b952cec5150e8281187595637f91";
  }

  static const char* value(const ::ros_imu_pub::imu_data_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1347b952cec5150eULL;
  static const uint64_t static_value2 = 0x8281187595637f91ULL;
};

template<class ContainerAllocator>
struct DataType< ::ros_imu_pub::imu_data_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ros_imu_pub/imu_data";
  }

  static const char* value(const ::ros_imu_pub::imu_data_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ros_imu_pub::imu_data_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# GPS data includes two latitude readings, two longitude readings, and two sspeed over ground readings\n\
\n\
float32 heading\n\
float32 roll\n\
float32 pitch\n\
float32 lin_x\n\
float32 lin_y\n\
float32 lin_z\n\
";
  }

  static const char* value(const ::ros_imu_pub::imu_data_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ros_imu_pub::imu_data_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.heading);
      stream.next(m.roll);
      stream.next(m.pitch);
      stream.next(m.lin_x);
      stream.next(m.lin_y);
      stream.next(m.lin_z);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct imu_data_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ros_imu_pub::imu_data_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ros_imu_pub::imu_data_<ContainerAllocator>& v)
  {
    s << indent << "heading: ";
    Printer<float>::stream(s, indent + "  ", v.heading);
    s << indent << "roll: ";
    Printer<float>::stream(s, indent + "  ", v.roll);
    s << indent << "pitch: ";
    Printer<float>::stream(s, indent + "  ", v.pitch);
    s << indent << "lin_x: ";
    Printer<float>::stream(s, indent + "  ", v.lin_x);
    s << indent << "lin_y: ";
    Printer<float>::stream(s, indent + "  ", v.lin_y);
    s << indent << "lin_z: ";
    Printer<float>::stream(s, indent + "  ", v.lin_z);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROS_IMU_PUB_MESSAGE_IMU_DATA_H
