// Generated by gencpp from file ros_gps_pub/gps_data.msg
// DO NOT EDIT!


#ifndef ROS_GPS_PUB_MESSAGE_GPS_DATA_H
#define ROS_GPS_PUB_MESSAGE_GPS_DATA_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ros_gps_pub
{
template <class ContainerAllocator>
struct gps_data_
{
  typedef gps_data_<ContainerAllocator> Type;

  gps_data_()
    : latitude1(0.0)
    , latitude2(0.0)
    , longitude1(0.0)
    , longitude2(0.0)
    , sog1(0.0)
    , sog2(0.0)  {
    }
  gps_data_(const ContainerAllocator& _alloc)
    : latitude1(0.0)
    , latitude2(0.0)
    , longitude1(0.0)
    , longitude2(0.0)
    , sog1(0.0)
    , sog2(0.0)  {
  (void)_alloc;
    }



   typedef float _latitude1_type;
  _latitude1_type latitude1;

   typedef float _latitude2_type;
  _latitude2_type latitude2;

   typedef float _longitude1_type;
  _longitude1_type longitude1;

   typedef float _longitude2_type;
  _longitude2_type longitude2;

   typedef float _sog1_type;
  _sog1_type sog1;

   typedef float _sog2_type;
  _sog2_type sog2;





  typedef boost::shared_ptr< ::ros_gps_pub::gps_data_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ros_gps_pub::gps_data_<ContainerAllocator> const> ConstPtr;

}; // struct gps_data_

typedef ::ros_gps_pub::gps_data_<std::allocator<void> > gps_data;

typedef boost::shared_ptr< ::ros_gps_pub::gps_data > gps_dataPtr;
typedef boost::shared_ptr< ::ros_gps_pub::gps_data const> gps_dataConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ros_gps_pub::gps_data_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ros_gps_pub::gps_data_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ros_gps_pub

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'ros_gps_pub': ['/home/ubuntu/catkin_ws/src/ROS_gps_pub/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ros_gps_pub::gps_data_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_gps_pub::gps_data_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_gps_pub::gps_data_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_gps_pub::gps_data_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_gps_pub::gps_data_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_gps_pub::gps_data_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ros_gps_pub::gps_data_<ContainerAllocator> >
{
  static const char* value()
  {
    return "240f581cba0734ba766965d88f37634c";
  }

  static const char* value(const ::ros_gps_pub::gps_data_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x240f581cba0734baULL;
  static const uint64_t static_value2 = 0x766965d88f37634cULL;
};

template<class ContainerAllocator>
struct DataType< ::ros_gps_pub::gps_data_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ros_gps_pub/gps_data";
  }

  static const char* value(const ::ros_gps_pub::gps_data_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ros_gps_pub::gps_data_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# GPS data includes two latitude readings, two longitude readings, and two sspeed over ground readings\n\
\n\
float32 latitude1\n\
float32 latitude2\n\
float32 longitude1\n\
float32 longitude2\n\
float32 sog1\n\
float32 sog2\n\
";
  }

  static const char* value(const ::ros_gps_pub::gps_data_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ros_gps_pub::gps_data_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.latitude1);
      stream.next(m.latitude2);
      stream.next(m.longitude1);
      stream.next(m.longitude2);
      stream.next(m.sog1);
      stream.next(m.sog2);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct gps_data_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ros_gps_pub::gps_data_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ros_gps_pub::gps_data_<ContainerAllocator>& v)
  {
    s << indent << "latitude1: ";
    Printer<float>::stream(s, indent + "  ", v.latitude1);
    s << indent << "latitude2: ";
    Printer<float>::stream(s, indent + "  ", v.latitude2);
    s << indent << "longitude1: ";
    Printer<float>::stream(s, indent + "  ", v.longitude1);
    s << indent << "longitude2: ";
    Printer<float>::stream(s, indent + "  ", v.longitude2);
    s << indent << "sog1: ";
    Printer<float>::stream(s, indent + "  ", v.sog1);
    s << indent << "sog2: ";
    Printer<float>::stream(s, indent + "  ", v.sog2);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROS_GPS_PUB_MESSAGE_GPS_DATA_H
