// Generated by gencpp from file ros_i2cpwm_board_sub/ServosConfig.msg
// DO NOT EDIT!


#ifndef ROS_I2CPWM_BOARD_SUB_MESSAGE_SERVOSCONFIG_H
#define ROS_I2CPWM_BOARD_SUB_MESSAGE_SERVOSCONFIG_H

#include <ros/service_traits.h>


#include <ros_i2cpwm_board_sub/ServosConfigRequest.h>
#include <ros_i2cpwm_board_sub/ServosConfigResponse.h>


namespace ros_i2cpwm_board_sub
{

struct ServosConfig
{

typedef ServosConfigRequest Request;
typedef ServosConfigResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ServosConfig
} // namespace ros_i2cpwm_board_sub


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ros_i2cpwm_board_sub::ServosConfig > {
  static const char* value()
  {
    return "29a8ed89c4fc7505dd84e9625c298b65";
  }

  static const char* value(const ::ros_i2cpwm_board_sub::ServosConfig&) { return value(); }
};

template<>
struct DataType< ::ros_i2cpwm_board_sub::ServosConfig > {
  static const char* value()
  {
    return "ros_i2cpwm_board_sub/ServosConfig";
  }

  static const char* value(const ::ros_i2cpwm_board_sub::ServosConfig&) { return value(); }
};


// service_traits::MD5Sum< ::ros_i2cpwm_board_sub::ServosConfigRequest> should match 
// service_traits::MD5Sum< ::ros_i2cpwm_board_sub::ServosConfig > 
template<>
struct MD5Sum< ::ros_i2cpwm_board_sub::ServosConfigRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ros_i2cpwm_board_sub::ServosConfig >::value();
  }
  static const char* value(const ::ros_i2cpwm_board_sub::ServosConfigRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_i2cpwm_board_sub::ServosConfigRequest> should match 
// service_traits::DataType< ::ros_i2cpwm_board_sub::ServosConfig > 
template<>
struct DataType< ::ros_i2cpwm_board_sub::ServosConfigRequest>
{
  static const char* value()
  {
    return DataType< ::ros_i2cpwm_board_sub::ServosConfig >::value();
  }
  static const char* value(const ::ros_i2cpwm_board_sub::ServosConfigRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ros_i2cpwm_board_sub::ServosConfigResponse> should match 
// service_traits::MD5Sum< ::ros_i2cpwm_board_sub::ServosConfig > 
template<>
struct MD5Sum< ::ros_i2cpwm_board_sub::ServosConfigResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ros_i2cpwm_board_sub::ServosConfig >::value();
  }
  static const char* value(const ::ros_i2cpwm_board_sub::ServosConfigResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_i2cpwm_board_sub::ServosConfigResponse> should match 
// service_traits::DataType< ::ros_i2cpwm_board_sub::ServosConfig > 
template<>
struct DataType< ::ros_i2cpwm_board_sub::ServosConfigResponse>
{
  static const char* value()
  {
    return DataType< ::ros_i2cpwm_board_sub::ServosConfig >::value();
  }
  static const char* value(const ::ros_i2cpwm_board_sub::ServosConfigResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROS_I2CPWM_BOARD_SUB_MESSAGE_SERVOSCONFIG_H
